### ISSUE TITLE
Transfer to signing git commits with SSH key

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/dotfiles#1]
Since `git` version 2.34 it supports signing commits with SSH keys instead of GPG keys.

This blog posts has a great writeup on how to configure this: https://calebhearth.com/sign-git-with-ssh

Unfortunately GitHub doesn't yet support verifying commits through SSH keys and only supports GPG keys for now.

**Comment by budimanjojo** [comment]
> Unfortunately GitHub doesn't yet support verifying commits through SSH keys and only supports GPG keys for now.

This is no longer true btw :)

**Comment by bjw-s** [comment]
Haha, I actually forgot that I still had this issue open. Not sure if I still want to go through the "trouble" of switching now though
